import AVAXLogo from '@/images/logos/avalanche.png'
import BTCLogo from '@/images/logos/Bitcoin.png'
import ETHLogo from '@/images/logos/Ethereum.jpg'

export const assets = [
  {
    name: 'Bitcoin',
    ticker: 'BTC',
    vasp: 'Binance',
    accType: 'subaccount',
    amount: 71897,
    realizedPL: 70946,
    realizedPLPerc: '12',
    unrealizedPL: 12000,
    unrealizedPLPerc: '8',
    totalPL: 82946,
    totalPLPerc: '28',
    logo: BTCLogo,
  },
  {
    name: 'Bitcoin',
    ticker: 'BTC',
    vasp: 'Coinhako',
    accType: 'subaccount',
    amount: 72897,
    realizedPL: 71946,
    realizedPLPerc: '6',
    unrealizedPL: 3000,
    unrealizedPLPerc: '4',
    totalPL: 75946,
    totalPLPerc: '15',
    logo: BTCLogo,
  },
  {
    name: 'Avalanche',
    ticker: 'AVAX',
    vasp: 'Binance',
    accType: 'subaccount',
    amount: 1897,
    realizedPL: 21946,
    realizedPLPerc: '10',
    unrealizedPL: 42000,
    unrealizedPLPerc: '32',
    totalPL: 68946,
    totalPLPerc: '31',
    logo: AVAXLogo,
  },
  {
    name: 'Ethereum',
    ticker: 'ETH',
    vasp: 'Binance',
    accType: 'subaccount',
    amount: 72097,
    realizedPL: 12946,
    realizedPLPerc: '9',
    unrealizedPL: 42000,
    unrealizedPLPerc: '20',
    totalPL: 62946,
    totalPLPerc: '29',
    logo: ETHLogo,
  },
]
